# Generated by Django 6.1 on 2026-08-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, help_text='Nom ou pseudo du visiteur', max_length=120)),
                ('message', models.TextField(help_text='Le texte du témoignage')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Note optionnelle (1-5)', null=True)),
                ('approved', models.BooleanField(default=True, help_text='Si vrai, le témoignage est visible publiquement')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-date_created'],
            },
        ),
    ]
