# Generated by Django 6.1 on 2026-08-30 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='type_categorie',
            field=models.CharField(choices=[('livre', 'Livre'), ('service', 'Service')], default='livre', help_text='Détermine si cette catégorie regroupe des livres ou des services', max_length=10),
        ),
        migrations.AlterField(
            model_name='livre',
            name='couverture',
            field=models.ImageField(help_text='Photo de couverture / illustration principale', upload_to='couvertures/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='fichier',
            field=models.FileField(blank=True, help_text='Fichier réel, jamais exposé publiquement. Laisser vide pour un service.', null=True, upload_to='fichiers_proteges/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='LivreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galerie/%Y/%m/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.livre')),
            ],
            options={
                'verbose_name': 'Image de galerie',
                'verbose_name_plural': 'Images de galerie',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
