# Generated by Django 6.1 on 2026-08-31 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_categorie_type_categorie_alter_livre_couverture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=0, help_text='Prix en FCFA', max_digits=10)),
                ('couverture', models.ImageField(help_text='Image de couverture principale', upload_to='services/couvertures/%Y/%m/')),
                ('disponible', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('whatsapp_phone', models.CharField(blank=True, help_text='Numéro utilisé pour le contact WhatsApp (ex: 2376...)', max_length=32)),
                ('sous_categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.souscategorie')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/galerie/%Y/%m/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.service')),
            ],
            options={
                'verbose_name': 'Image de service',
                'verbose_name_plural': 'Images de service',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
