# Generated by Django 6.1 on 2026-08-31 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_service_serviceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='document',
            field=models.FileField(blank=True, help_text='Document attaché (PDF, DOCX, ...)', null=True, upload_to='services/documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='service',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL vers une vidéo (YouTube, Vimeo, etc.)', max_length=500),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('items', models.TextField(blank=True, help_text='Liste des éléments demandés (texte libre ou JSON).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='quotes/%Y/%m/')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.categorie')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-created_at'],
            },
        ),
    ]
