# Generated by Django 6.1 on 2026-09-01 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_service_document_service_video_url_quote'),
    ]

    def _migrate_items_to_json(apps, schema_editor):
        import json
        Quote = apps.get_model('catalog', 'Quote')
        for q in Quote.objects.all():
            val = q.items
            if val is None or val == "":
                # ensure a valid JSON list
                q.items = json.dumps([])
                q.save()
                continue
            if isinstance(val, str):
                try:
                    # if already valid JSON, leave as-is
                    json.loads(val)
                except Exception:
                    # wrap text into a single-entry list
                    q.items = json.dumps([val])
                    q.save()

    operations = [
        migrations.AddField(
            model_name='quote',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='quote',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(_migrate_items_to_json, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='quote',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='QuoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quotes/images/%Y/%m/')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.quote')),
            ],
            options={
                'verbose_name': 'Image de devis',
                'verbose_name_plural': 'Images de devis',
            },
        ),
    ]
