# Generated by Django 6.1 on 2026-09-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_quote_address_quote_event_date_alter_quote_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='prix_estime',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Prix estimé en FCFA (optionnel)', max_digits=12, null=True),
        ),
    ]
