# Generated by Django 6.1 on 2026-09-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_quote_prix_estime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eloquence',
            fields=[
            ],
            options={
                'verbose_name': "Élément d'Éloquence",
                'verbose_name_plural': "Éléments d'Éloquence",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.service',),
        ),
        migrations.AddField(
            model_name='service',
            name='video',
            field=models.FileField(blank=True, help_text="Fichier vidéo (mp4, webm, ...) pour les éléments d'Éloquence", null=True, upload_to='services/videos/%Y/%m/'),
        ),
    ]
