# Generated by Django 6.1 on 2026-09-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_eloquence_service_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compteur de visites',
                'verbose_name_plural': 'Compteur de visites',
            },
        ),
    ]
