# Generated by Django 6.1 on 2026-08-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_code', models.CharField(default='000000', max_length=20)),
                ('merchant_number', models.CharField(default='696618526', max_length=20)),
            ],
            options={
                'verbose_name': 'Payment configuration',
                'verbose_name_plural': 'Payment configuration',
            },
        ),
    ]
