# Generated by Django 6.1 on 2026-09-07 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_eloquence_service_video'),
        ('purchases', '0002_paymentconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyen_paiement', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money')], default='orange_money', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('paye', 'Payé'), ('echoue', 'Échoué')], default='en_attente', max_length=15)),
                ('reference_transaction', models.CharField(blank=True, help_text="Référence renvoyée par l'agrégateur de paiement", max_length=100)),
                ('montant', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats_service', to='catalog.service')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_achats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Achat de service',
                'verbose_name_plural': 'Achats de services',
                'ordering': ['-date_achat'],
                'unique_together': {('utilisateur', 'service')},
            },
        ),
    ]
